/** Persian UI strings for the Telegram bot (fa-first, RTL-safe). */
export const fa = {
  welcome: "👋 خوش آمدید!\nاز این ربات می‌توانید کانفیگ تهیه کنید، کانفیگ تست بگیرید و کانفیگ‌های فعال خود را مدیریت کنید.",
  mainMenu: "منوی اصلی:",
  buy: "🛒 خرید کانفیگ",
  trial: "🧪 کانفیگ تست",
  myConfigs: "📂 کانفیگ‌های من",
  paymentGuide: "💳 راهنمای پرداخت",
  support: "📞 پشتیبانی",
  help: "ℹ️ راهنما",
  choosePlan: "پلن مورد نظر را انتخاب کنید:",
  planCard: (name: string, price: string, days: number, gb: number, devices: number, gaming: boolean) =>
    `📦 ${name}\n💰 قیمت: ${price} تومان\n⏳ مدت: ${days} روز\n📊 ترافیک: ${gb} گیگابایت\n📱 دستگاه: ${devices}${gaming ? "\n🎮 گیمینگ" : ""}`,
  payInstructions: (text: string) => `💳 پس از واریز، رسید خود را ارسال کنید:\n\n${text}`,
  sendReceipt: "📸 ارسال رسید پرداخت",
  cancel: "❌ انصراف",
  orderRegistered: "✅ سفارش شما ثبت شد. پس از تایید مدیر، کانفیگ برای شما ارسال می‌شود.",
  orderApproved: "✅ پرداخت شما تایید شد! کانفیگ شما آماده است:",
  orderRejected: (reason?: string) => `❌ سفارش شما تایید نشد.${reason ? `\nدلیل: ${reason}` : ""}\nدر صورت نیاز با پشتیبانی در تماس باشید.`,
  trialOffer: (remaining: number) => `🧪 کانفیگ تست رایگان (حداکثر ۱۰۰ مگابایت)\nتست‌های باقی‌مانده: ${remaining}`,
  trialNone: "❌ تست رایگان شما به پایان رسیده است. برای تهیه کانفیگ از منوی خرید استفاده کنید.",
  trialCreated: "✅ کانفیگ تست شما ساخته شد:",
  myConfigsList: "کانفیگ‌های شما:",
  active: "🟢 فعال",
  lowTraffic: "🟠 در حال اتمام ترافیک",
  expired: "🔴 منقضی",
  subDetail: (name: string, usedGb: string, totalGb: string, daysLeft: number) =>
    `📦 ${name}\n📊 مصرف: ${usedGb} از ${totalGb} گیگابایت\n⏳ ${daysLeft} روز باقی‌مانده`,
  getLink: "🔗 دریافت لینک",
  getQr: "📷 QR",
  getUsage: "📊 مصرف",
  getDns: "🌐 دریافت DNS",
  rename: "✏️ تغییر نام",
  back: "🔙 بازگشت",
  askName: "✏️ نام دلخواه کانفیگ را بفرستید (حداکثر ۲۰ حرف):",
  nameTooLong: "❌ نام نباید بیش از ۲۰ حرف باشد. دوباره بفرستید:",
  nameInvalid: "❌ نام معتبر نیست (فقط حروف، اعداد، فاصله، - و _ ). دوباره بفرستید:",
  nameOk: (final: string) => `✅ نام کانفیگ: ${final}`,
  linkCopied: "🔗 لینک اشتراک شما (در کلاینت وارد کنید):",
  dnsHeader: "🌐 DNS گیمینگ:",
  paymentGuideText: "💳 راهنمای پرداخت:\n۱. پلن را انتخاب کنید\n۲. مبلغ را واریز کنید\n۳. اسکرین‌شات رسید را ارسال کنید\n۴. پس از تایید مدیر، کانفیگ ارسال می‌شود",
  supportText: "📞 پشتیبانی: با مدیر در تماس باشید.",
  helpText: "ℹ️ راهنما:\n— خرید: انتخاب پلن، واریز، ارسال رسید\n— تست: حداکثر ۲ بار، ۱۰۰ مگابایت\n— کانفیگ‌های من: مشاهده مصرف و لینک‌ها",
  error: "❌ خطایی رخ داد. دوباره تلاش کنید.",
  // admin chat
  adminNewOrder: (plan: string, price: string, userName: string, handle: string, uid: number, note: string, orderId: string) =>
    `📥 سفارش جدید #${orderId.slice(0, 8)}\n\n📦 پلن: ${plan}\n💰 قیمت: ${price} تومان\n👤 ${userName} (${handle})\n🆔 ${uid}${note ? `\n📝 ${note}` : ""}`,
  approveBtn: "✅ تایید و ساخت کانفیگ",
  rejectBtn: "❌ رد کردن",
  rejectReasonPrompt: "دلیل رد را بفرستید (یا /skip):",
  orderApprovedCard: "✅ تایید شد — کانفیگ ساخته و ارسال شد",
  orderRejectedCard: "❌ رد شد",
  alreadyProcessed: "این سفارش قبلاً پردازش شده است.",
  adminStats: (sales: number, activeSubs: number, trials: number, nodesOnline: number, nodesTotal: number) =>
    `📊 آمار امروز:\n💰 فروش: ${sales}\n📦 اشتراک فعال: ${activeSubs}\n🧪 تست‌ها: ${trials}\n🩺 نودها: ${nodesOnline}/${nodesTotal} آنلاین`,
  pendingOrders: "📥 سفارش‌های در انتظار:",
  noPendingOrders: "سفارش در انتظاری وجود ندارد.",
};
